apiVersion: v1
kind: Service
metadata:
  name: goapi
  namespace: default
spec:
  ports:
  - port: 9000
    name: goapi
  clusterIP: None
  selector:
    app: goapi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: goapi
  namespace: default
spec:
  selector:
    matchLabels:
      app: goapi # has to match .spec.template.metadata.labels
  serviceName: "goapi"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: goapi # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: goapi
        image: test:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
          name: web